replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/vac-testes/qualificar-partes-git
  tag: latest
  pullPolicy: Always

service:
  port: 80
  targetPort: 8080

app:
  name: qualificar-partes
