resources:
  - ../../base

namePrefix: dev-

namespace: vac-testes

images:
  - name: qualificar-partes
    newName: tjpa-registry-quay-quay-enterprise.apps.ocp-hub.i.tj.pa.gov.br/ca/qualificar-partes
    newTag: "1.0.0"

patches:
  - target:
      kind: Deployment
      name: qualificar-partes
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Route
      name: qualificar-partes
    patch: |-
      - op: replace
        path: /spec/to/name
        value: dev-qualificar-partes
